no js

diff --git a/.github/workflows/frontend-linting.yml b/.github/workflows/frontend-linting.yml
--- a/.github/workflows/frontend-linting.yml
+++ b/.github/workflows/frontend-linting.yml
@@ -37,20 +37,20 @@ jobs:
     - name: Run ESLint
       run: |
         cd src/frontend
-        npx eslint . --ext .js,.ts,.tsx
+        npx eslint . --ext .ts,.tsx
 
     - name: Check Prettier formatting
       run: |
         cd src/frontend
         npx prettier --check .
 
-    - name: Run Prettier (if check fails)
-      if: failure()
-      run: |
-        cd src/frontend
-        npx prettier --write .
-        git config user.name github-actions
-        git config user.email github-actions@github.com
-        git add .
-        git commit -m "Apply Prettier formatting" || echo "No changes to commit"
-        git push
+    # - name: Run Prettier (if check fails)
+    #   if: failure()
+    #   run: |
+    #     cd src/frontend
+    #     npx prettier --write .
+    #     git config user.name github-actions
+    #     git config user.email github-actions@github.com
+    #     git add .
+    #     git commit -m "Apply Prettier formatting" || echo "No changes to commit"
+    #     git push
